language: java
sudo: false

cache:
  directories:
  - $HOME/.m2

script:
  - mvn test -B
  - mvn appengine:deploy -Dapp.deploy.project=receipts-187b6 -Dappengine.additionalParams="--service_account_json_key_file=receipts-dev-deploy.json"

before_install:
- openssl aes-256-cbc -K $encrypted_4bd8af1e2f1a_key -iv $encrypted_4bd8af1e2f1a_iv -in receipts-dev-deploy.json.enc -out receipts-dev-deploy.json -d
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install -y kubectl google-cloud-sdk google-cloud-sdk-app-engine-java

#before_script:
#  - gcloud auth activate-service-account "deployment@receipts-187b6.iam.gserviceaccount.com" --key-file=receipts-dev-deploy.json
#  - gcloud config set project receipts-187b6